// <auto-generated />
namespace Inventon.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Nowe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nowe));
        
        string IMigrationMetadata.Id
        {
            get { return "201511142053187_Nowe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
