//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventon.DAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventonDatabaseEntities : DbContext
    {
        public InventonDatabaseEntities()
            : base("name=InventonDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<KategoriaTable> KategoriaTable { get; set; }
        public DbSet<ProducentTable> ProducentTable { get; set; }
        public DbSet<ProduktTable> ProduktTable { get; set; }
        public DbSet<ProduktZamowienieTable> ProduktZamowienieTable { get; set; }
        public DbSet<StatusZamowieniaTable> StatusZamowieniaTable { get; set; }
        public DbSet<ZamowienieTable> ZamowienieTable { get; set; }
    }
}
