//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Inventon.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class ProduktTable
    {
        public ProduktTable()
        {
            this.ProduktZamowienieTable = new HashSet<ProduktZamowienieTable>();
        }
    
        public int id { get; set; }
        public string ProduktNazwa { get; set; }
        public string ProduktOpis { get; set; }
        public string ProduktCena { get; set; }
        public Nullable<System.DateTime> ProduktDataDodania { get; set; }
        public Nullable<int> ProduktProducentId { get; set; }
        public int KategoriaId { get; set; }

        [Column(TypeName = "image")]
        [MaxLength]
        public byte[] Obrazek { get; set; }
   
        public virtual KategoriaTable KategoriaTable { get; set; }
        public virtual ProducentTable ProducentTable { get; set; }
        public virtual ICollection<ProduktZamowienieTable> ProduktZamowienieTable { get; set; }
    }
}
